spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_product_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8084